version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - '5502:80'
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - DB_HOST=db   
  db:
    image: mysql:latest
    ports:
    - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'BipartPass'
      MYSQL_DATABASE: 'Clientes_db'
      MYSQL_USER: 'bipart'
      MYSQL_PASSWORD: 'bipart'
        
    