version: "3.8"
services:
  web:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 5502:80
    volumes:
      - ./client:/usr/share/nginx/html
  db_bipart:
    image: mysql:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    restart: always
    depends_on:
      - db_bipart
    links:
      - db_bipart
    env_file: ./.env
    volumes:
      - C:/Users/mauri/Documents/Veps:/app/VEPS
    ports:
      - $PORT:$DOCKER_PORT

volumes:
  mysql-data:
