version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - '5501:80'
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: mysql:5.7
    ports:
    - '3307:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true 
      MYSQL_DATABASE: clientes_db
    command: --skip-name-resolve
    