FROM node:latest
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm i
#Instala dependencias de Chromium y otras dependencias necesarias
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

#Variables de entorno para puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"
# Instalar Puppeteer
RUN npm install puppeteer
# If you are building your code for production
# RUN npm ci --omit=dev
# Bundle app source
ADD server /usr/src/app/
ADD client /usr/src/app/

# Expose a port for the app to listen on
EXPOSE 4000
#Start the app
CMD [ "node", "index.js"]