version: '3.8'  
services:
  web:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 5502:80
    volumes:
      - ./client:/usr/share/nginx/html
  db:
    image: mysql:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
    - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    restart: always
    depends_on:
      - db
    links:
      - db  
    env_file: ./.env
    ports:
      - $PORT:$DOCKER_PORT
        
volumes:
  mysql-data: